### PR TITLE
Mac version

### PR DESCRIPTION
**Pull request by arolson101**
This adds Mac support to the nuget package.

- Makefile: move frameworks into a Framework/$(Platform) folder
- Version: up patch version to 3.1.6.1 so that the major version stays pinned to PureLayout's
- .nuspec: add <Files> section with the build outputs for iOS and macOS

I don't know how you build the package itself but I moved the .nuspec to the solution level and I built a package by running ```nuget build PureLayout.Net``` in the solution folder.  I see there's nuget package info in both the .nuspec and the .csproj.

Note also that the Mac project uses the iOS project's AssemblyInfo.cs via a file link to keep them in sync.

This addresses #5

### CODE REVIEW

**Comment by mallibone** [comment]
Thank you for the PR 🙂  - The sample project is missing the mac project which is referenced in the solution. Could you add it to your PR?

**Comment by arolson101** [comment]
I'm not very familiar with github and pull requests, but I think that it's updated with the mac sample app

**Comment by mallibone** [comment]
Thanks 🙂

**Comment by arolson101** [comment]
Publish to nuget?

**Comment by mallibone** [comment]
I am on it, still have some cleaning up todo. And should not take as long as it did to merge it 🙈

**Comment by arolson101** [comment]
could you publish to Nuget?

**Comment by arolson101** [comment]
it's been a while; can you publish to NuGet?

**Pull request merged**
